package com.swedbank.park.ui.pojo;

import lombok.Getter;
import lombok.Setter;

import java.sql.Date;

/**
 * This class holds the ticket details generated by the system and displayed to the user
 */

@Getter
@Setter
public class TicketInfo {
    private long ticketId;
    private long startTime;
    private long endTime;
    private Date date;

    private SlotInfo slot;

    public TicketInfo(){}

    public TicketInfo(SlotInfo slot, long startTime, Date date) {
        this.slot = slot;
        this.startTime = startTime;
        this.date = date;
    }
    public TicketInfo(long ticketId, SlotInfo slot, long startTime, Date date) {
        this.ticketId = ticketId;
        this.slot = slot;
        this.startTime = startTime;
        this.date = date;
    }


}
