-- MySQL Script generated by MySQL Workbench
-- 13/04/22 23:34:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema id17729995_park_swedbank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema id17729995_park_swedbank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `id17729995_park_swedbank` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `id17729995_park_swedbank` ;

-- -----------------------------------------------------
-- Table `id17729995_park_swedbank`.`slot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id17729995_park_swedbank`.`slot` ;

CREATE TABLE IF NOT EXISTS `id17729995_park_swedbank`.`slot` (
  `slot_number` BIGINT NOT NULL,
  `width` DECIMAL(2,2) NULL,
  `height` DECIMAL(2,2) NULL,
  `is_available` TINYINT(1) NULL DEFAULT 1,
  `create_user` VARCHAR(50) NULL DEFAULT 'SYS',
  `create_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_user` VARCHAR(50) NULL DEFAULT 'SYS',
  `update_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`slot_number`)
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id17729995_park_swedbank`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id17729995_park_swedbank`.`ticket` ;

CREATE TABLE IF NOT EXISTS `id17729995_park_swedbank`.`ticket` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `slot_number` BIGINT NOT NULL,
  `start_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `end_time` DATETIME NULL,
  `create_user` VARCHAR(50) NULL DEFAULT 'SYS',
  `create_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_user` VARCHAR(50) NULL DEFAULT 'SYS',
  `update_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_ticket_slot1_idx` (`slot_number` ASC),
  CONSTRAINT `fk_ticket_slot1`
    FOREIGN KEY (`slot_number`)
    REFERENCES `id17729995_park_swedbank`.`slot` (`slot_number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id17729995_park_swedbank`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id17729995_park_swedbank`.`payment` ;

CREATE TABLE IF NOT EXISTS `id17729995_park_swedbank`.`payment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `ticket_id` BIGINT NOT NULL,
  `price` DECIMAL(14,2) NULL,
  `create_user` VARCHAR(50) NULL DEFAULT 'SYS',
  `create_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  
  PRIMARY KEY (`id`),
  INDEX `fk_payment_ticket1_idx` (`ticket_id` ASC),
  CONSTRAINT `fk_payment_ticket1`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `id17729995_park_swedbank`.`ticket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
	)
ENGINE = InnoDB;